version: '3.9'

services:

  database:
    image: mysql:latest
    container_name: blog_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: admin
  web:
    image: nginx

